### ISSUE TITLE
There's no Favicon to the website.

### ISSUE THREAD

**Issue by Shelbybosss** [Omkar-Sonawane-23/VedicVani#132] opened 2024-05-16 13:59 UTC
I Will add a suitable favicon for the website which will make it look good in tab and easily recogniseable

**Comment by Shelbybosss** [comment] 2024-05-16 13:59
@Omkar-Sonawane-23 can you assign me this issue

**Comment by sameer-soni** [comment] 2024-05-16 17:13
duplicate of #70

**Closed by sameer-soni** 2024-05-16 17:13 UTC
